modLoader="javafml"
loaderVersion="[43,)"
issueTrackerURL="https://github.com/CreativeMD/ItemPhysicLite/issues"
license="LGPL-3.0-only"

[[mods]]
    modId="itemphysiclite"
    logoFile="itemphysiclite.png"
    version="1.5.2"
    displayName="ItemPhysicLite"
    displayURL="https://modrinth.com/mod/itemphysic-lite"
    displayTest="IGNORE_SERVER_VERSION"
    authors="CreativeMD"
    description='''Enhances the rendering of items.'''

[[dependencies.itemphysiclite]]
    modId="forge"
    mandatory=true
    versionRange="[43.2,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.itemphysiclite]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.2,1.19.3)"
    ordering="NONE"
    side="BOTH"

[[dependencies.itemphysiclite]]
   modId="creativecore"
   mandatory=true
   ordering="NONE"
   side="BOTH"
   versionRange="2.11.27"

